{% set name = "elasticsearch-dbapi" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elasticsearch-dbapi-{{ version }}.tar.gz
  sha256: cd58e0092638090ba94b084e26d6ac34f45170d568f9caaf7e3db37fc9fe3b86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elasticsearch >=7.0.1
    - python >=3.6
    - sqlalchemy
    # not listed upstream but testing fails without it:
    - packaging

test:
  imports:
    - es
    - es.elastic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/preset-io/elasticsearch-dbapi
  summary: A DBAPI and SQLAlchemy dialect for Elasticsearch
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/preset-io/elasticsearch-dbapi
  doc_url: https://github.com/preset-io/elasticsearch-dbapi

extra:
  recipe-maintainers:
    - xylar
