{% set name = "elasticsearch-dbapi" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elasticsearch-dbapi-{{ version }}.tar.gz
  sha256: 809db9a62bab66b83298f6e85b1f2413f78ed27195fc3ba978d6d7e003a0fa93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - elasticsearch >7,<7.14
    - packaging >=21.0,<22.0
    # not listed upstream but import test fails without it
    - six
    - sqlalchemy

test:
  imports:
    - es
    - es.elastic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/preset-io/elasticsearch-dbapi
  summary: A DBAPI and SQLAlchemy dialect for Elasticsearch
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/preset-io/elasticsearch-dbapi
  doc_url: https://github.com/preset-io/elasticsearch-dbapi

extra:
  recipe-maintainers:
    - xylar
