{% set name = "elasticsearch-dbapi" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elasticsearch-dbapi-{{ version }}.tar.gz
  sha256: 003c68ad4d2ea2dfc57fe6ad2d776ab592bf36395f9924e8efe53e0b2fe451ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - elasticsearch >7,<7.14
    - packaging >=21.0,<22.0
    - sqlalchemy

test:
  imports:
    - es
    - es.elastic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/preset-io/elasticsearch-dbapi
  summary: A DBAPI and SQLAlchemy dialect for Elasticsearch
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/preset-io/elasticsearch-dbapi
  doc_url: https://github.com/preset-io/elasticsearch-dbapi

extra:
  recipe-maintainers:
    - xylar
